### ISSUE TITLE
Add zoomify to Galaxy EU

### ISSUE THREAD

**Issue by tbrown91** [lldelisle/tools-lldelisle#16]
Sorry, I didn't know the best way to contact you.

As I'm still learning about the process of incorporating tools into Galaxy, I feel I've missed the crucial step of getting from this repo into Galaxy. I have a feeling I need to put a pull request somewhere else, but I can't remember where.

@bgruening can you also help with this?

Many thanks,

Tom

**Comment by bgruening** [comment]
Uppsi. Good question.

The tools are now in the ToolShed. So Admins of your favorite Galaxy instance can install them.
In the case of EU you can also add those tools to https://github.com/usegalaxy-eu/usegalaxy-eu-tools/blob/master/lldelisle.yaml as a PR.

This is your way to request official tools. If merged, the tools will be installed each weekend.

**Comment by tbrown91** [comment]
Ok, I will add it to the yaml and make a PR

**Comment by tbrown91** [comment]
https://github.com/usegalaxy-eu/usegalaxy-eu-tools/pull/711

**Comment by bgruening** [comment]
Cool, thanks. Can you close the issue please?
